version: "3"

services:

  # s0ster
  s0str:
    build: .
    container_name: s0ster
    environment:
      debug_level: DEBUG
      pubkey: "d66f63fe2d946e8a02dda5f35d3f14808c59cd2a9df1a64803ffe6e19c1f1b0d"
      pg_host: db
      pg_user: postgres
      pg_pass: testpass
    ports:
      - 8080:8080
    links:
      - "s0str-db:db"

  # postgres
  s0str-db:
    image: postgres:alpine
    container_name: s0ster-db
    environment:
      POSTGRES_DB: s0ster
      POSTGRES_PASSWORD: testpass
